export const normalizeTicket = (ticket) => ({
    id: ticket.Issue_Id,
    issueId: ticket.Issue_Id,
    title: ticket.Title,
    ticketKey: ticket.Issue_Code,
    status: ticket.Status,
    navId: ticket.Issue_Id,
    statusId: ticket.StatusId,
    description: ticket.HtmlDesc || ticket.Description,
    assignedTo: ticket.Assignee_Id,
    assginedName: ticket.Assignee_Name,
    estimateHours: ticket.hours || ticket.Hours,
    createdAt: ticket.CreatedAt,
    updatedAt: ticket.UpdatedAt,
    updatedBy: ticket.UpdatedBy,
    repoId: ticket.RepoId,
    dueDate: ticket.Due_Date,
    project: ticket.Project_Id,
    ProjKey: ticket.ProjKey,
    RepoKey: ticket.RepoKey,
    reopenedBy: ticket.ReopenedBy,
    priority: ticket.Priority,
    // Safely parse JSON strings, fallback to empty arrays if null/invalid
    multiAssignees: ticket.All_Assignees ? JSON.parse(ticket.All_Assignees) : [],
    label: ticket.Labels_JSON ? JSON.parse(ticket.Labels_JSON) : [],
    CompletionPct: ticket.CompletionPct,
    teamId: ticket.Assignee_TeamId,
    teamName: ticket.Assignee_TeamName,
    overallPercentage: ticket.OverallPercentage,
    isCloseRequested: ticket.IsCloseRequested,
});