/* =============================================================================
   Messenger E2EE — Step 3: 1:1 conversations and encrypted messages
   -----------------------------------------------------------------------------
   The server never sees message text. Each message is AES-256-GCM encrypted in
   the browser with a random content key; that content key is wrapped separately
   for every recipient device (ECDH with the device's signed pre-key + HKDF +
   AES-KW) and stored in ChatMessageKeys.

   ChatConversations        one row per conversation (Type = 'Direct' for now)
   ChatConversationMembers  who is in a conversation
   ChatEncryptedMessages    ciphertext + metadata needed to decrypt
   ChatMessageKeys          content key wrapped for one recipient device

   Requires chat_e2ee_keys.sql (Step 1) to have been run first.
   ============================================================================= */
USE [WGNEST]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'[dbo].[ChatConversations]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ChatConversations](
        [ConversationId] [uniqueidentifier] NOT NULL CONSTRAINT [DF_ChatConversations_Id] DEFAULT (NEWID()),
        [Type]           [varchar](20)      NOT NULL,   -- Direct (Group comes in a later step)
        [DirectKey]      [varchar](80)      NULL,       -- "<smaller userId>|<larger userId>" for Direct, NULL otherwise
        [CreatedBy]      [uniqueidentifier] NOT NULL,
        [CreatedAt]      [datetime]         NOT NULL,
        [LastMessageAt]  [datetime]         NULL,
        CONSTRAINT [PK_ChatConversations] PRIMARY KEY CLUSTERED ([ConversationId] ASC)
    ) ON [PRIMARY]
END
GO

-- Exactly one direct conversation per pair of users
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ChatConversations_DirectKey')
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ChatConversations_DirectKey]
        ON [dbo].[ChatConversations] ([DirectKey])
        WHERE [DirectKey] IS NOT NULL
GO

IF OBJECT_ID(N'[dbo].[ChatConversationMembers]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ChatConversationMembers](
        [MemberId]       [uniqueidentifier] NOT NULL CONSTRAINT [DF_ChatConversationMembers_Id] DEFAULT (NEWID()),
        [ConversationId] [uniqueidentifier] NOT NULL,
        [UserId]         [uniqueidentifier] NOT NULL,
        [JoinedAt]       [datetime]         NOT NULL,
        CONSTRAINT [PK_ChatConversationMembers] PRIMARY KEY CLUSTERED ([MemberId] ASC),
        CONSTRAINT [FK_ChatConversationMembers_Conversation] FOREIGN KEY ([ConversationId])
            REFERENCES [dbo].[ChatConversations] ([ConversationId])
    ) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ChatConversationMembers_Conversation_User')
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ChatConversationMembers_Conversation_User]
        ON [dbo].[ChatConversationMembers] ([ConversationId], [UserId])
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ChatConversationMembers_User')
    CREATE NONCLUSTERED INDEX [IX_ChatConversationMembers_User]
        ON [dbo].[ChatConversationMembers] ([UserId]) INCLUDE ([ConversationId])
GO

IF OBJECT_ID(N'[dbo].[ChatEncryptedMessages]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ChatEncryptedMessages](
        [MessageId]          [uniqueidentifier] NOT NULL CONSTRAINT [DF_ChatEncryptedMessages_Id] DEFAULT (NEWID()),
        [ConversationId]     [uniqueidentifier] NOT NULL,
        [SenderUserId]       [uniqueidentifier] NOT NULL,
        [SenderDeviceId]     [uniqueidentifier] NOT NULL,
        [ClientMessageId]    [uniqueidentifier] NOT NULL,   -- generated by the sender; makes retries idempotent
        [Ciphertext]         [varchar](max)     NOT NULL,   -- base64 AES-256-GCM (includes auth tag)
        [Iv]                 [varchar](24)      NOT NULL,   -- base64 12-byte GCM nonce
        [EphemeralPublicKey] [varchar](512)     NOT NULL,   -- base64 SPKI, P-256, one per message
        [CreatedAt]          [datetime]         NOT NULL,
        CONSTRAINT [PK_ChatEncryptedMessages] PRIMARY KEY CLUSTERED ([MessageId] ASC),
        CONSTRAINT [FK_ChatEncryptedMessages_Conversation] FOREIGN KEY ([ConversationId])
            REFERENCES [dbo].[ChatConversations] ([ConversationId])
    ) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ChatEncryptedMessages_Conversation_CreatedAt')
    CREATE NONCLUSTERED INDEX [IX_ChatEncryptedMessages_Conversation_CreatedAt]
        ON [dbo].[ChatEncryptedMessages] ([ConversationId], [CreatedAt] DESC)
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ChatEncryptedMessages_Sender_ClientMessageId')
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ChatEncryptedMessages_Sender_ClientMessageId]
        ON [dbo].[ChatEncryptedMessages] ([SenderUserId], [ClientMessageId])
GO

IF OBJECT_ID(N'[dbo].[ChatMessageKeys]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ChatMessageKeys](
        [MessageKeyId]      [uniqueidentifier] NOT NULL CONSTRAINT [DF_ChatMessageKeys_Id] DEFAULT (NEWID()),
        [MessageId]         [uniqueidentifier] NOT NULL,
        [RecipientUserId]   [uniqueidentifier] NOT NULL,
        [RecipientDeviceId] [uniqueidentifier] NOT NULL,
        [PreKeyId]          [int]              NOT NULL,   -- which of the device's signed pre-keys was used
        [WrappedKey]        [varchar](128)     NOT NULL,   -- base64 AES-KW wrapped 32-byte content key
        CONSTRAINT [PK_ChatMessageKeys] PRIMARY KEY CLUSTERED ([MessageKeyId] ASC),
        CONSTRAINT [FK_ChatMessageKeys_Message] FOREIGN KEY ([MessageId])
            REFERENCES [dbo].[ChatEncryptedMessages] ([MessageId])
    ) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ChatMessageKeys_Message_Device')
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ChatMessageKeys_Message_Device]
        ON [dbo].[ChatMessageKeys] ([MessageId], [RecipientDeviceId])
GO
